apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: skopeo-lsm5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: skopeo-lsm5
    app.kubernetes.io/part-of: skopeo-1
  name: skopeo-lsm5
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: skopeo-lsm5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: skopeo-lsm5
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/lmandvek-tenant/skopeo-1/skopeo-lsm5@sha256:af27f583448cf1d1c34b56945a04048b5ed161ecea0a4fdd70dc5079da94a5d6
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
